get https://cms-backend-lr46.onrender.com/api/contents/

### 
put https://cms-backend-lr46.onrender.com/api/contents/1
Content-Type :application/json 

{
    "title": "Update content "
}

### 
delete https://cms-backend-lr46.onrender.com/api/contents/1